apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# You could use a namespace per ingress IP:
# namespace: undying-proxy-123-123-123-123  # set in a Kustomize overlay

resources:
- deployment.undying-proxy.yaml
- namespace.undying-proxy.yaml
- role.undying-proxy.yaml
- roleBinding.undying-proxy.yaml
- service.undying-proxy-metrics.yaml
- service.undying-proxy-tcp.yaml
- service.undying-proxy-udp.yaml
- serviceAccount.undying-proxy.yaml

images:
- name: controller
  newName: my-repo/undying-proxy
  newTag: latest
- name: my-repo/undying-proxy
  newTag: v0.0.1
