---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: undying-proxy
  namespace: undying-proxy
  labels:
    app: undying-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: undying-proxy
subjects:
- kind: ServiceAccount
  name: undying-proxy
