---
apiVersion: v1
kind: Service
metadata:
  name: undying-proxy
  namespace: undying-proxy
  labels:
    app: undying-proxy
spec:
  type: LoadBalancer
  loadBalancerIP: changeme  # set in a Kustomize overlay
  externalTrafficPolicy: Local
  selector:
    app: undying-proxy
  ports:
  # NOTE: this Service's `ports` section is managed by this operator by default.
  #   The rest of the Service's configuration must be managed by you.
  #   If using ArgoCD or similar, you'll want to IgnoreDifferences on the `ports` section.

  # any-port has the purpose of passing validation during a kubectl apply, consider choosing a port that won't be used by an UnDyingProxy.
  - name: any-port
    port: 1234
    targetPort: 1234
    protocol: UDP
