---
apiVersion: v1
kind: Service
metadata:
  name: undying-proxy-metrics
  namespace: undying-proxy
  labels:
    app: undying-proxy
spec:
  type: ClusterIP
  selector:
    app: undying-proxy
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
