# permissions for end users to view undyingproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: undying-proxy
    app.kubernetes.io/managed-by: kustomize
  name: undyingproxy-viewer-role
rules:
- apiGroups:
  - proxy.sfact.io
  resources:
  - undyingproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.sfact.io
  resources:
  - undyingproxies/status
  verbs:
  - get
